---
title: "Mon fichier"
author: Gilles
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document:
    toc: true
    toc_depth: 3
bibliography: biblio.bib
---

```{r setup, include=FALSE}
options(scipen = 999)
knitr::opts_chunk$set(echo = TRUE,
                      # fig.align='center',
                      # fig.pos='H',
                      # out.width = "90%",
                      # out.height="90%",
                      warning=FALSE,
                      message=FALSE)
```

\clearpage

# Partie 1

Ceci sera la partie 1

Sourcer le fichier 1

```{r source1, eval=TRUE}
source(file = "./source1.R",
       encoding = "utf-8",
       local = TRUE)
```


## Section 1

```{r test, eval=TRUE}
df <- data.frame(a=1:10,
                 b=101:110,
                 c=letters[1:10])

df
```

## Section 2

Un graphique

```{r plot, eval=TRUE}
plot(df)
```

\clearpage

# Partie 2

```{r mtcars}
knitr::kable(mtcars[1:5, 1:5], caption = "The mtcars data.")
```

Utilisation de la variable initialisée dans `source1.R`

```{r testsource1, echo=TRUE}
barplot(height = abc$b, names.arg = abc$c)
```

\clearpage

# Partie 3

Test de citation [@knuth_literate_prog]

\clearpage

# Partie 4

## Section 1
## Section 2
## Section 3
## Section 4

\clearpage

# Bibliographie
